# -*- coding: utf-8 -*-
"""gabriel ec 970.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW_ACTpAgiCldOrhlUhGdiCidx3PslJ_
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install \
  --force-reinstall \
  --no-deps \
  git+https://github.com/hemanth-asirvatham/GABRIEL-prerelease.git@main

# Commented out IPython magic to ensure Python compatibility.
# %pip install openai

import os
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
# %pip install aiolimiter # run this too

import gabriel
from gabriel.utils.plot_utils import regression_plot, bar_plot, box_plot, line_plot
import os
import pandas as pd

os.environ['OPENAI_API_KEY'] = "YOUR OPENAPI KEY GOES HERE"

# Create a toy spreadshseet. This will work well with text from any language!
toy_data = pd.DataFrame({"text": [
    "Following last quarter’s review, I’m confident we can ship the analytics dashboard by Friday with the current headcount.",
    "I’m drowning in tickets; the build keeps failing and it’s wearing me down.",
    "Today’s walk by the bay shook off the fog in my head; I feel ready to try again.",
    "The rollout was mismanaged; we flagged the risk repeatedly and were summarily ignored.",
    "Preliminary analyses suggest the intervention achieved measurable improvements across key outcomes.",
    "My calendar is stacked, sleep is thin, but I think we can thread the needle if we cut scope.",
    "Let’s merge—benchmarks beat baseline and the regressions look contained.",
    "Honestly, I’m lost; nothing I do seems to move the needle and it’s exhausting.",
    "The exhibition balanced restraint with daring; a surprisingly confident curatorial voice."
]})
# You can load real data using df = pd.read_csv("path_to_your_spreadsheet"). See the 'Loading your data' section for more info

# Define the features we want to measure
attributes = {
    "focus on work life": "How much the text centers on jobs, projects, deadlines, meetings, or professional goals (0 = not about work, 100 = entirely about work).",
    "optimism": "How positive and forward-looking the text feels (near 0 = pessimistic/hopeless, near 100 = highly hopeful and upbeat).",
    "anger": "How much frustration, irritation, or hostility is expressed (near 0 = none, 100 = very angry).",
    "formality": "How formal, structured, and professional the language is (near 0 = very casual/slangy, near 100 = highly formal/academic).",
    "confidence": "How self-assured the speaker sounds about claims or outcomes (near 0 = doubtful/uncertain, near 100 = very certain/assertive).",
    "personal stress": "How strained, overwhelmed, or anxious the speaker sounds (near 0 = calm/relaxed, near 100 = extremely stressed)."
}

additional_instructions = "" #### Any additional instructions you want to pass to the model when rating. For instance examples of how to rate the text

#Make the call to the package
results = await gabriel.rate(
    df = toy_data,      # if using real data, substitute 'toy_data' with 'df'
    column_name = "text",       # name of column with text to rate
    attributes = attributes,    # attributes to score on 0–100 scale; defined above
    additional_instructions = additional_instructions,
    save_dir = "toy_rate",      # directory to save results, use a Google Drive folder (e.g. "/content/drive/folder") for permanent storage (see 'Loading your data' section)
    model = "gpt-5-mini",       # GPT model used for ratings
    n_runs = 1,                 # number of rating passes per text (higher = averaged over more ratings)
    reasoning_effort = 'low',   # amount of reasoning effort, 'medium' is default
    modality = "text",  # input modality can also be "entity" (for terms like 'apple pie', not full texts), "web" (see web section), "image", or "audio" (see multimodal section)
    reset_files = False,
)

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/MyDrive/Partisan Views on Migration.xlsx')

attributes = {
    "warmth": (
        "How warm, welcoming, and positive the tone is toward immigrants and "
        "immigration. Near 0 = very hostile, punitive, exclusionary. "
        "Near 100 = very positive, inclusive, empathetic, and welcoming."
    )
}

additional_instructions = ""  # you can add examples here if you want

async def rate_party_column(df, text_col, save_dir, model="gpt-5-mini"):
    """
    df       : DataFrame with a text column (e.g. 'Democrat' or 'Republican')
    text_col : name of the column to rate
    save_dir : directory where GABRIEL can save intermediate files
    model    : OpenAI model for ratings
    """
    os.makedirs(save_dir, exist_ok=True)

    results = await gabriel.rate(
        df=df,
        column_name=text_col,
        attributes=attributes,
        additional_instructions=additional_instructions,
        save_dir=save_dir,
        model=model,
        n_runs=1,
        reasoning_effort='low',
        modality="text",
        reset_files=False,
    )

    return results

async def rate_party_platforms(df):
    # Make sure the column names match your spreadsheet
    # If they differ, adjust here (e.g. 'Democratic party' -> 'Democrat')
    assert "Democrat" in df.columns, df.columns
    assert "Republican" in df.columns, df.columns

    # 1) Rate Democratic text
    dem_results = await rate_party_column(
        df=df.copy(),
        text_col="Democrat",
        save_dir="/content/gabriel_platforms/dem"
    )

    # 2) Rate Republican text
    rep_results = await rate_party_column(
        df=df.copy(),
        text_col="Republican",
        save_dir="/content/gabriel_platforms/rep"
    )

    # 3) Attach warmth scores back to original df
    # By design, GABRIEL returns the original columns + one column per attribute.
    # Since we used attributes = {"warmth": "..."},
    # the output should have a 'warmth' column.
    df["dem_warmth"] = dem_results["warmth"].values
    df["rep_warmth"] = rep_results["warmth"].values

    return df

# Run the rating coroutine (Colab supports top-level await)
df_rated = await rate_party_platforms(df)

df_rated[["Year", "dem_warmth", "rep_warmth"]]

attributes = {
    "pathways_emphasis": (
        "How strongly the text emphasizes creating or expanding pathways to legal "
        "status, permanent residency, or citizenship for immigrants. Near 0 = "
        "no mention or opposition; near 100 = strong support, prioritization, or "
        "positive framing of legalization or regularization pathways."
    ),
    "strengthening_border": (
        "How strongly the text emphasizes enhancing border security, including "
        "enforcement, surveillance, policing, physical barriers, deterrence, penalties, "
        "or restricting entry. Near 0 = little or no enforcement emphasis; near 100 = "
        "heavy focus on border security and enforcement."
    ),
    "tolerance_illegal_migrants": (
        "How tolerant, empathetic, or accommodative the text is toward unauthorized "
        "('illegal') immigrants. Near 0 = punitive, criminalizing; near 100 = humane, "
        "protective, emphasizing rights or compassion."
    ),
    "acceptance_refugees": (
        "How welcoming and supportive the text is toward refugees and asylum seekers. "
        "Near 0 = opposition or restrictive framing; near 100 = humanitarian, protective, "
        "promoting resettlement or refuge."
    ),
}

additional_instructions = ""

async def rate_party_column(df, text_col, party_label, save_dir, model="gpt-5-mini"):
    """
    df         : DataFrame
    text_col   : name of column with platform text ('Democrat' or 'Republican')
    party_label: short label used in output col names ('dem' or 'rep')
    save_dir   : directory for GABRIEL temp files
    """
    os.makedirs(save_dir, exist_ok=True)

    results = await gabriel.rate(
        df=df,
        column_name=text_col,
        attributes=attributes,
        additional_instructions=additional_instructions,
        save_dir=save_dir,
        model=model,
        n_runs=1,
        reasoning_effort='low',
        modality="text",
        reset_files=True, # Added this to ensure new attributes are used
    )

    print(f"\nColumns returned for {party_label}: {list(results.columns)}")

    # Add one column per attribute, with prefix (e.g. dem_pathways_emphasis)
    for attr_name in attributes.keys():
        if attr_name not in results.columns:
            raise ValueError(
                f"Expected attribute '{attr_name}' not found in results. "
                f"Got columns: {results.columns}"
            )
        df[f"{party_label}_{attr_name}"] = results[attr_name].values

    return df

async def rate_party_platforms(df):
    assert "Democrat" in df.columns, df.columns
    assert "Republican" in df.columns, df.columns

    # Democrats
    df = await rate_party_column(
        df=df,
        text_col="Democrat",
        party_label="dem",
        save_dir="/content/gabriel_platforms/dem",
    )

    # Republicans
    df = await rate_party_column(
        df=df,
        text_col="Republican",
        party_label="rep",
        save_dir="/content/gabriel_platforms/rep",
    )

    return df

df = pd.read_excel('/content/drive/MyDrive/Partisan Views on Migration.xlsx')

attributes = {
    "cultural_threat": (
    "How much the text portrays immigrants as threatening American culture, values, "
    "traditions, language, or national identity. Near 0 = emphasizes multiculturalism, "
    "integration, or cultural enrichment; near 100 = emphasizes cultural threat, "
    "assimilation failure, or protecting American identity."
),

    "immigrants_take_jobs": (
        "How strongly the text expresses or implies that immigrants take jobs from "
        "American workers, depress wages, or harm natives economically. "
        "Near 0 = rejects this idea or emphasizes immigrants boosting the economy; "
        "near 100 = explicitly or implicitly claims immigrants take jobs or harm U.S. workers."
    ),
}

df_rated = await rate_party_platforms(df)

df_rated[[
    "Year",
    "dem_immigrants_take_jobs",
    "rep_immigrants_take_jobs",
    "dem_cultural_threat",
    "rep_cultural_threat"
]]

df_plot = df.sort_values("Year")

fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharex=False, sharey=False)

# ---------------------------
# 1. Immigrants Take Jobs
# ---------------------------
ax = axes[0]

ax.plot(df_plot["Year"], df_plot["dem_immigrants_take_jobs"],
        marker="o", color="blue", label="Democrat", linewidth=2)

ax.plot(df_plot["Year"], df_plot["rep_immigrants_take_jobs"],
        marker="o", color="red", label="Republican", linewidth=2)

ax.set_title("Rhetoric: Immigrants Take American Jobs (1992–2024)", fontsize=13)
ax.set_xlabel("Year")
ax.set_ylabel("Rating (0–100)")
ax.set_xticks(df_plot["Year"])
ax.set_xticklabels(df_plot["Year"], rotation=45)
ax.grid(True, linestyle="--", alpha=0.35)

# ---------------------------
# 2. Cultural Threat Emphasis
# ---------------------------
ax = axes[1]

ax.plot(df_plot["Year"], df_plot["dem_cultural_threat"],
        marker="o", color="blue", label="Democrat", linewidth=2)

ax.plot(df_plot["Year"], df_plot["rep_cultural_threat"],
        marker="o", color="red", label="Republican", linewidth=2)

ax.set_title("Rhetoric: Immigrants Threaten American Culture (1992–2024)", fontsize=13)
ax.set_xlabel("Year")
ax.set_ylabel("Rating (0–100)")
ax.set_xticks(df_plot["Year"])
ax.set_xticklabels(df_plot["Year"], rotation=45)
ax.grid(True, linestyle="--", alpha=0.35)

# Shared legend across both plots
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc="lower center", ncol=2, frameon=False)

plt.tight_layout(rect=[0, 0.08, 1, 1])
plt.show()

import matplotlib.pyplot as plt

# Make sure your data are sorted by year
df_plot = df_rated.sort_values("Year")

# (attribute column suffix, panel title)
panels = [
    ("pathways_emphasis",          "Emphasis on Pathways to Legal Status"),
    ("strengthening_border",       "Emphasis on Strengthening the Border"),
    ("tolerance_illegal_migrants", "Tolerance of Unauthorized Immigrants"),
    ("acceptance_refugees",        "Acceptance of Refugees & Asylum Seekers"),
]

fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharex=True, sharey=True)
axes = axes.flatten()

for ax, (attr, title) in zip(axes, panels):
    # Democrat line
    ax.plot(
        df_plot["Year"],
        df_plot[f"dem_{attr}"],
        marker="o",
        label="Democrat"
    )

    # Republican line
    ax.plot(
        df_plot["Year"],
        df_plot[f"rep_{attr}"],
        marker="o",
        label="Republican"
    )

    ax.set_title(title)
    ax.set_xlabel("Year")
    ax.set_ylabel("Rating (0–100)")
    ax.grid(True, linestyle="--", alpha=0.4)

# Put a single legend for the whole figure (top center)
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc="upper center", ncol=2)

fig.suptitle(
    "Immigration Rhetoric in Party Platforms, 1992–2024\n"
    "(GABRIEL ratings: higher = more emphasis/support)",
    y=0.98
)

fig.tight_layout(rect=[0, 0, 1, 0.93])
plt.show()

# Ensure sorted by year
df_plot = df_rated.sort_values("Year")

# (attribute column suffix, panel title)
panels = [
    ("pathways_emphasis",          "Emphasis on Pathways to Legal Status"),
    ("strengthening_border",       "Emphasis on Strengthening the Border"),
    ("tolerance_illegal_migrants", "Tolerance of Unauthorized Immigrants"),
    ("acceptance_refugees",        "Acceptance of Refugees & Asylum Seekers"),
]

fig, axes = plt.subplots(2, 2, figsize=(13, 9), sharex=True, sharey=True)
axes = axes.flatten()

for ax, (attr, title) in zip(axes, panels):
    # Democrats: Blue
    ax.plot(
        df_plot["Year"],
        df_plot[f"dem_{attr}"],
        marker="o",
        color="blue",
        label="Democrat"
    )

    # Republicans: Red
    ax.plot(
        df_plot["Year"],
        df_plot[f"rep_{attr}"],
        marker="o",
        color="red",
        label="Republican"
    )

    ax.set_title(title, fontsize=12)
    ax.set_xlabel("Year")
    ax.set_ylabel("Rating (0–100)")
    ax.set_xticks(df_plot["Year"])     # <-- Explicitly label years on each subplot
    ax.set_xticklabels(df_plot["Year"], rotation=45)
    ax.grid(True, linestyle="--", alpha=0.35)

# === Combined Legend (moved down so it doesn't overlap) ===
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(
    handles,
    labels,
    loc="upper center",
    ncol=2,
    frameon=False,
    bbox_to_anchor=(0.5, 0.92)   # <-- LOWERED LEGEND POSITION
)

fig.suptitle(
    "Immigration Rhetoric in U.S. Party Platforms, 1992–2024\n(GABRIEL Ratings: Higher = More Emphasis/Support)",
    y=0.99,
    fontsize=14
)

fig.tight_layout(rect=[0, 0, 1, 0.90])  # <-- Leaves room for legend & title
plt.show()